apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana
      containers:
        - name: grafana
          image: grafana/grafana:10.4.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          volumeMounts:
            - name: ds
              mountPath: /etc/grafana/provisioning/datasources
            - name: db-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /tmp/dashboards
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

        - name: sidecar
          image: kiwigrid/k8s-sidecar:1.27.0
          env:
            - name: LABEL
              value: grafana_dashboard
            - name: LABEL_VALUE
              value: "1"
            - name: FOLDER
              value: /tmp/dashboards
            - name: NAMESPACE
              value: monitoring
          volumeMounts:
            - name: dashboards
              mountPath: /tmp/dashboards
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 192Mi

      volumes:
        - name: ds
          configMap:
            name: grafana-datasource
        - name: db-provider
          configMap:
            name: grafana-dashboards-provider
        - name: dashboards
          emptyDir: {}
