apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-reader
rules:
- apiGroups: [""]
  resources: ["configmaps", "services"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "get", "list", "patch", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-workflows
roleRef:
  kind: ClusterRole
  name: backup-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-storage
  namespace: argo-workflows
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-storage-binding
  namespace: argo-workflows
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-workflows
roleRef:
  kind: Role
  name: backup-storage
  apiGroup: rbac.authorization.k8s.io